on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", "amd64", "arm64"]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        asset_name: docker-sriov-plugin-${{ matrix.goos }}-${{ matrix.goarch }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md ibdev2netdev docker-sriov-plugin.service
        ldflags: '-X main.version=$RELEASE_TAG'
