name: Publish plugin
on: 
  release:
    types: [created]

jobs:
  publish_plugin:
    name: publish plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux"]
        goarch: ["amd64", "arm64", "ppc64le", "riscv64", "s390x"]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        asset_name: docker-sriov-plugin-${{ matrix.goos }}-${{ matrix.goarch }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md docker-sriov-plugin.service
        ldflags: '-X main.version=${{ github.ref_name }}'
        sha256sum: true
        md5sum: false
